#TR-62 - Register development
TableRise/tablerise-frontend pull request #10
Opened 2024-08-14 01:52 UTC by RasecMH

### Technical Checklist

* [ ] Garanti que todos os fluxos criados possuem testes E2E.
* [ ] A pipeline foi executada com sucesso e a cobertura de testes atingiu ou passou de 90%.
* [ ] Ao finalizar a task enviei o link da PR no discord para aprovação.

⚠️ Cuidado com os arquivos e informações sensíveis, nenhuma informação secreta deve ser enviada ao github, tais como:

.npmrc, secrets, senhas, strings de conexão de prod e etc...

### Additional Notes

[ The quality of your code is the resume of your work ]

This Pull Request successfully Closes #TaskID

2024-08-26 01:33 UTC, Adson-Gomes-Oliveira requested changes

2024-08-26 01:33 UTC, Adson-Gomes-Oliveira commented on .gitignore
O diretório do cypress deve conter apenas estes arquivos:

![image](https://github.com/user-attachments/assets/eebec084-a293-4a12-a480-ab141eafca03)

Remover estes e fazer git pull de develop.

2024-08-26 01:33 UTC, Adson-Gomes-Oliveira commented on public/images/LogoTablerise.svg
Já existe o arquivo logo.svg na pasta assets/icons/logo.svg, não é necessário este arquivo aqui.

2024-08-26 01:33 UTC, Adson-Gomes-Oliveira commented on src/components/home/Features.tsx
> +import MapIconHome from '../../../assets/icons/map-icon-home.svg?url';
Porque a adição desses `?url` ?

2024-08-26 01:33 UTC, Adson-Gomes-Oliveira commented on svgr.d.ts
Porque essas declarações aqui?

2024-08-26 05:54 UTC, RasecMH commented on .gitignore
Eu já deletei e fiz um git pull, só para ficar claro, os arquivos que estão aparecendo aqui pra mim são apenas o screenshots além desses que mostrou, e desses arquivos que está falando?

Mesmo depois do gitpull os arquivos se mantém aparecendo aqui, na minha máquina não aparecem mais, mas aqui ainda está aparecendo, esses arquivos são gerados quando roda o cypress

2024-08-26 05:55 UTC, RasecMH commented on public/images/LogoTablerise.svg
Para poder modificar as cores do svg eu instalei o svg-webpack, para poder acessar o svg com ele é necessário que o arquivo esteja na pasta public se não ele não reconhece.

A tag IMAGE do next não permite manipular as propriedades do svg.

2024-08-26 05:57 UTC, RasecMH commented on src/components/home/Features.tsx
> +import MapIconHome from '../../../assets/icons/map-icon-home.svg?url';
O svg-webpack transforma os svgs em funções jsx, e você não pode passar uma função jsx via props no next, para usar como uma string/url é necessário colocar o parametro ?url.

2024-08-26 05:58 UTC, RasecMH commented on svgr.d.ts
Isso é para configuração do svg-webpack.

2024-08-26 05:58 UTC, RasecMH commented on svgr.d.ts
Isso é para configuração do svg-webpack.

2024-08-26 06:06 UTC, RasecMH commented on public/images/LogoTablerise.svg
Para poder trocar a cor do svg eu precisei instalar o svg-webpack e para ele acessar imagens é necessário que o arquivo esteja na pasta public.

A tag IMAGE do next não permite mudar as propriedades de um svg.

2024-08-26 06:07 UTC, RasecMH commented on .gitignore
Feito.

2024-08-26 06:23 UTC, RasecMH commented on public/images/LogoTablerise.svg
Removido

2024-09-16 06:15 UTC, Adson-Gomes-Oliveira approved these changes

2024-09-20 06:47 UTC, merged