Feat/TR- 61/Login Page Development
TableRise/tablerise-frontend pull request #11
Opened 2024-08-15 01:03 UTC by AmandaPtela

### Technical Checklist

* [ ] Garanti que todos os fluxos criados possuem testes E2E.
* [ ] A pipeline foi executada com sucesso e a cobertura de testes atingiu ou passou de 90%.
* [ ] Ao finalizar a task enviei o link da PR no discord para aprovação.

⚠️ Cuidado com os arquivos e informações sensíveis, nenhuma informação secreta deve ser enviada ao github, tais como:

.npmrc, secrets, senhas, strings de conexão de prod e etc...

### Additional Notes

[ The quality of your code is the resume of your work ]

This Pull Request successfully Closes #TaskID

2024-08-18 15:07 UTC, ashtrindade commented on src/components/login/Form.tsx
> +    function handleLogin(data: any) {
É interessante que nomes de funções sejam autoexplicativos, isso também já elimina a necessidade de comentários adicionais no código.

por exemplo:
```suggestion
    function getLoginDataFromContext(data: any) {
```

2024-08-18 15:10 UTC, ashtrindade commented on src/components/login/input.tsx
> +    function handleInput(value: string, type: string) {
Aqui também pode utilizar um nome mais explícito

exemplo:
```suggestion
    function getEmailAndPassword(value: string, type: string) {        
```

2024-08-18 15:23 UTC, ashtrindade commented on src/components/login/Form.tsx
> +        "response = api.post({data}"
É interessante manter o padrão de aspas simples, você pode instalar o plugin do Eslint no vscode para encontrar esses problemas de estilo durante o desenvolvimento.

```suggestion
        'response = api.post({data}'
```

2024-08-21 01:01 UTC, AmandaPtela commented on src/components/login/Form.tsx
> +    function handleLogin(data: any) {
Essa função vai ser a responsável só pelo login mesmo, por isso o nome.
Obrigada pela observação!

2024-08-21 01:02 UTC, AmandaPtela commented on src/components/login/Form.tsx
> +        "response = api.post({data}"
Ajustado!

2024-08-21 01:06 UTC, AmandaPtela commented on src/components/login/input.tsx
> +    function handleInput(value: string, type: string) {
Ajustada.
Agora é uma função de validação.

2024-08-21 12:57 UTC, mariosanseverino commented on src/components/login/LoginForm.tsx
Senti falta da tipagem dos useStates e do retorno das funções `validateInput` e `handleLogin`. No caso dos useState, `useState<boolean>(false)` é um exemplo de tipagem de estado para aceitar apenas valores booleanos.

2024-08-22 00:20 UTC, AmandaPtela commented on src/components/login/LoginForm.tsx
Os comentários e os console.log vão ser removidos assim que a lógica e a refatoração estiverem completas.
Utilizo eles pra me guiar durante o desenvolvimento. 😄 
Quanto à tipagem, vou ajustar isso.
Obrigada!

2024-10-02 20:29 UTC, Adson-Gomes-Oliveira requested changes

2024-10-02 20:29 UTC, Adson-Gomes-Oliveira commented on src/app/login/page.tsx
> +            <div className="flex flex-col w-2/5 z-10 h-screen absolute justify-center items-center bg-white rounded-l-lg text-left">
As estilizações devem ser feitas em um arquivo.css separado.

Toda pasta que possuí paginas e componentes existe uma pasta styles e dentro dessa pasta devem ficar os  estilos.

Sugiro dar uma olhada na branch de develop e nas pastas app e components para entender como o css está sendo organizado. CSS no tsx só em casos muito específicos e necessários.

2024-10-02 20:29 UTC, Adson-Gomes-Oliveira commented on src/app/page.tsx
> +import Login from './login/page';
Login é uma página aqui ficam os componentes da Home

2024-10-02 20:29 UTC, Adson-Gomes-Oliveira commented on src/components/login/LoginForm.tsx
> +                const token = await getToken();
O token é setado no navegador do usuário quando o login é realizado, essa lógica contempla isso? Não entendi muito bem.

2024-10-02 20:29 UTC, Adson-Gomes-Oliveira commented on src/components/login/LoginForm.tsx
> +        return 'dados inválidos';
Tem alguma utilização para esse return?

2024-10-02 20:29 UTC, Adson-Gomes-Oliveira commented on src/components/login/LoginForm.tsx
> +                {/* salvar response do login no localstorage e token nos cookies (1dia)redirecionar p home */}
O token já é salvo nos cookies pelo backend, o front precisa apenas salvar o response do login no local storage.

2024-10-02 20:29 UTC, Adson-Gomes-Oliveira commented on src/components/login/dist/LoginForm.js
Não subir esse arquivo.

2024-10-02 21:31 UTC, AmandaPtela commented on src/components/login/LoginForm.tsx
> +                {/* salvar response do login no localstorage e token nos cookies (1dia)redirecionar p home */}
comentário desatualizado.

2024-10-02 21:34 UTC, AmandaPtela commented on src/app/page.tsx
> +import Login from './login/page';
Faltou apagar.
Estava usando a Home pra visualizar antes de entender aquela questão de rotas. 😬

2024-10-02 22:03 UTC, AmandaPtela commented on src/components/login/LoginForm.tsx
> +                const token = await getToken();
Não contempla.
Irei consertar.

2024-10-02 23:53 UTC, AmandaPtela commented on src/components/login/LoginForm.tsx
> +        return 'dados inválidos';
só por questão de orientação própria durante o desenvolvimento.

2024-10-03 13:07 UTC, Adson-Gomes-Oliveira commented on src/components/login/LoginForm.tsx
> +        return 'dados inválidos';
OK, justo 😅

2025-01-16 13:02 UTC, closed without merging