#TR-62 - Add Wrapper
TableRise/tablerise-frontend pull request #15
Opened 2024-08-23 21:06 UTC by RasecMH

2024-08-24 02:48 UTC, Adson-Gomes-Oliveira commented
![image](https://github.com/user-attachments/assets/d9c724bd-dbd6-4e4e-aa08-f81467265785)

Creio que faltou adicionar a lib axios

2024-08-26 01:36 UTC, Adson-Gomes-Oliveira requested changes

2024-08-26 01:36 UTC, Adson-Gomes-Oliveira commented on cypress/e2e/home.cy.ts
Remover esse arquivo e dar git pull de develop

2024-08-26 19:49 UTC, JhonatasAnicezio approved these changes
Show de bola!

2024-09-16 06:16 UTC, Adson-Gomes-Oliveira approved these changes

2024-09-16 06:39 UTC, merged