#TR-68 - FAQ development
TableRise/tablerise-frontend pull request #8
Opened 2024-08-12 19:36 UTC by mariosanseverino

### Technical Checklist

* [ ] Garanti que todos os fluxos criados possuem testes E2E.
* [ ] A pipeline foi executada com sucesso e a cobertura de testes atingiu ou passou de 90%.
* [ ] Ao finalizar a task enviei o link da PR no discord para aprovação.

⚠️ Cuidado com os arquivos e informações sensíveis, nenhuma informação secreta deve ser enviada ao github, tais como:

.npmrc, secrets, senhas, strings de conexão de prod e etc...

### Additional Notes

[ The quality of your code is the resume of your work ]

This Pull Request successfully Closes #TaskID

2024-08-15 03:48 UTC, Adson-Gomes-Oliveira requested changes

2024-08-15 03:48 UTC, Adson-Gomes-Oliveira commented on src/app/page.tsx
> +import FAQ from './components/FAQ';
O padrão de import é path absoluto --> @/.../... [ Dê preferência a esse padrão ao desenvolver ]

2024-08-15 03:48 UTC, Adson-Gomes-Oliveira commented on src/app/components/ExpandBtn.tsx
> +            className='border border-color-greyScale/300 rounded-[4px] w-6 h-6 flex items-center justify-center'
Os estilos devem ser definidos em um arquivo separado.
Pode me procurar para te explicar melhor caso necessário.

2024-08-15 03:48 UTC, Adson-Gomes-Oliveira commented on src/app/components/FAQ.tsx
> +    const questions = [
Seria interessante que esse objeto estivesse em um path de utilidades, por exemplo:

`src/utils/faqQuestions.ts`

2024-08-15 03:48 UTC, Adson-Gomes-Oliveira commented on src/app/components/FAQ.tsx
> +                        key={ index }
Como key é interessante utilizar um id unico para não conflitar com outras keys existentes.
Pode conseguir isso com a lib uuidv4.

2024-08-15 03:48 UTC, Adson-Gomes-Oliveira commented on src/app/components/FAQ.tsx
> +        // The whole container
Os comentários devem ser removidos antes do merge em dev.

2024-08-15 03:48 UTC, Adson-Gomes-Oliveira commented on src/app/components/FAQItem.tsx
> +type FAQItemProps = {
As tipagens devem estar em uma pasta separada, crie uma pasta type e replique a estrutura de pastas dentro da pasta type, exemplo:

Se você precisa definir um tipo do arquivo FAQItem.tsx você pode cria-lo no path:

`src/types/modules/app/components/FAQItem.d.ts`

2024-08-15 03:54 UTC, Adson-Gomes-Oliveira requested changes

2024-08-15 03:54 UTC, Adson-Gomes-Oliveira commented on src/app/page.tsx
> +        <main className='w-full px-16 bg-[#141414]'>
Por enquanto deixe a tag principal sem estilização, além disso é importante utilizar os patterns do projeto para seguir a padronização. Todas as cores utilizadas do design tem suas respectivas variaveis definidas no tailwind.

2024-08-15 03:57 UTC, Adson-Gomes-Oliveira requested changes
A pasta components deve ficar fora da pasta app.

![image](https://github.com/user-attachments/assets/caacb7d5-216a-4e60-8b85-2c53f34e3a98)

Essa é a estrutura.

2024-08-17 01:32 UTC, Adson-Gomes-Oliveira requested changes
As perguntas do FAQ foram desenvolvidas em dark mode, porém como indicado no fim da descrição do card no JIRA, o desenvolvimento é apenas light mode no momento, segue o link do card:

https://tablerise.atlassian.net/jira/software/c/projects/TR/boards/3?quickFilter=10&selectedIssue=TR-68

Os componentes que podem ser reutilizados **devem** ficar na raiz da pasta components, os que vão servir apenas para uma página devem ficar na pasta correspondente, por exemplo, o FAQ vai existir apenas na home então o arquivo FAQ.tsx deve estar na pasta home.

O mesmo para o arquivo FAQItem.tsx

2024-08-20 04:08 UTC, Adson-Gomes-Oliveira requested changes

2024-08-20 04:08 UTC, Adson-Gomes-Oliveira commented on src/components/MoreDetailsIcon.tsx
Icones devem ser salvos na pasta assets/icons e utilizados com o component Image no next para melhor velocidade de carregamento, teve algum motivo pra esse icone ter sido construído assim?

2024-08-20 04:08 UTC, Adson-Gomes-Oliveira commented on src/types/modules/components/FAQItem.d.ts
Este arquivo deve estar dentro de uma pasta home, seguindo a estrutura de pastas do código principal.

2024-08-20 04:08 UTC, Adson-Gomes-Oliveira commented on src/components/ExpandIcon.tsx
Icones devem ser salvos na pasta assets/icons e utilizados com o component Image no next para melhor velocidade de carregamento, teve algum motivo pra esse icone ter sido construído assim?

2024-08-20 04:10 UTC, Adson-Gomes-Oliveira commented
O Vercel não está conseguindo finalizar o deploy, parece que há um erro de prettier:

![image](https://github.com/user-attachments/assets/6ffbc1c0-86f1-446d-8dc0-0274a882370f)

2024-08-20 12:37 UTC, mariosanseverino commented on src/components/MoreDetailsIcon.tsx
Não encontrei outra maneira de ajustar a cor dele de forma dinâmica, usando a cor da fonte.

2024-08-20 12:40 UTC, mariosanseverino commented on src/components/ExpandIcon.tsx
Esse componente renderiza um "+" ou "-" de acordo com o estado, além de usar a cor da fonte do container.

2024-08-20 18:49 UTC, mariosanseverino commented on src/types/modules/components/FAQItem.d.ts
Corrigido :+1:

2024-08-20 20:06 UTC, Adson-Gomes-Oliveira approved these changes

2024-08-20 20:20 UTC, ashtrindade approved these changes

2024-08-20 20:39 UTC, merged